var easy = ["Beans", "Broccoli", "Cabbage", "Carrot", "Celery", "Corn", "Cucumber",  "Lettuce", "Onion", "Peas", "Potato", "Pumpkin",  "Spinach", "Sweet Potato", "Tomato",  "Airplane", "Bicycle", "Boat", "Bus", "Car", "Helicopter", "Horse", "Jet", "Motorcycle", "Ship", "Subway", "Taxi", "Train", "Truck", "Apple", "Banana", "Cherry",  "Grapes", "Lemon", "Lime", "Melon", "Orange", "Peach", "Pear",  "Strawberry",
 "Watermelon", "Belt", "Boots", "Cap", "Coat", "Dress", "Gloves", "Hat", "Jacket", "Jeans", "Pajamas", "Pants", "Raincoat",
  "Scarf", "Shirt", "Shoes", "Skirt",  "Slippers", "Socks",  "Suit", "Sweater", "Sweatshirt", "T-shirt", "Tie",
   "Underpants", "Undershirt", "Alligator", "Ant", "Bear", "Bee", "Bird", "Camel", "Cat", "Cheetah", "Chicken",
    "Chimpanzee", "Cow", "Crocodile", "Deer", "Dog", "Dolphin", "Duck", "Eagle", "Elephant", "Fish", "Fly", "Fox",
    "Frog","Giraffe","Goat","Goldfish","Hamster","Hippopotamus","Horse","Kangaroo","Kitten","Lion","Lobster","Monkey",
    "Octopus","Owl","Panda","Pig","Puppy","Rabbit", "Cactus", "Volcano",
"Paris", "New York City", "Texas", "London", "Los Angeles", "Egypt", "Washington D.C.", "Mount Everest",  "The Grand Canyon", "Mount Rushmore",  "Hawaii",
"Albert Einstein",  "Michael Jordan", "Oprah", "Harry Potter", "Mickey Mouse", "Abraham Lincoln", "Beyoncé", "Taylor Swift",  "Spiderman", "Superman", "SpongeBob", "Yoda", "James Bond", "Darth Vader"]

var hard =["Turnip", "Tangerine","Slacks","Stockings",
"Eggplant", "Green Pepper", "Trousers",
"Radish",
"Asparagus",
"Bart Simpson","Grapefruit",
"Gandalf",
"Tom Cruise",
"David Beckham",
"Adele",
"Brad Pitt",
"Stephen Hawking",
"Conan O'Brien",
"Shanghai",
"Tokyo",
"Machu Pichu","Persimmon", "Pineapple", "Plum",
"Central Park",
"Easter Island",
"Yellowstone",
"Australia",
"Moscow",
"Dubai",
"Rome",
"Pawnshop",
"Copyright",
"Descendant",
"Tug Boat",
"Atlantis",
"Siesta",
"President",
"Voicemail",
"Emperor",
"Ironic",
"Opaque",
"Brunette",
"Dryer Sheet",
"Ruby",
"Robin",
"Ottoman",
"Welder",
"Gossip",
"Wallabee",
"Platypus",
"Fortnight",
"Segway",
"Elon Musk",
"Archimedes",
"Plato",
"Marcus Aurelius",
"Nero",
"Lao Zi",
"Confucious",
"Anteater",
"Istanbul",
"Prague",
"Fur",
"Snowshoe",
"Calzone",
"Helipad",
"Gollum",
"Houdini",
"Supernova",
"3D Printer",
"Toner",
"Dictator",
"Marxist",
"Libertarian",
"Bass Clef",
"Croissant",
"Cramp",
"Protestant",
"Catholic",
"Hearse",
"Rhyme"]
